/**
 * Centralized auth error code constants used within the feature
 */
export const AUTH_ERROR_CODES = {
  AUTH_INVALID_FIELDS: 'AUTH_INVALID_FIELDS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_REGISTRATION_FAILED: 'AUTH_REGISTRATION_FAILED',
  AUTH_CALLBACK_ERROR: 'AUTH_CALLBACK_ERROR',
  AUTH_EMAIL_VERIFICATION_REQUIRED: 'AUTH_EMAIL_VERIFICATION_REQUIRED',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
